image:https://img.shields.io/maven-central/v/org.sahli.asciidoc.confluence.publisher/asciidoc-confluence-publisher-maven-plugin.svg["Maven Central", link="http://central.maven.org/maven2/org/sahli/asciidoc/confluence/publisher/asciidoc-confluence-publisher/"]
image:https://img.shields.io/circleci/project/github/confluence-publisher/confluence-publisher/master.svg["Build Status", link="https://circleci.com/gh/confluence-publisher/confluence-publisher/tree/master"]
image:https://coveralls.io/repos/github/alainsahli/confluence-publisher/badge.svg?branch=master["Coverage Status", link="https://coveralls.io/github/alainsahli/confluence-publisher?branch=master"]

= Confluence Publisher

== Difference from the original

* This publisher publishes each file on `asciidocRootFolder` one by one with ignoring directory structure by default.
** You MUST write `:parent_title: Title of parent page` on asciidoc file subject to publish.
* If you want to execute as the original, you set `publishEachFile=false`.
** On this original mode, you can skip deletion of orphaned pages when set `skipDeleteOrphanedPages=true`
** On this original mode, you can set specify parent page by title (`ancestorTitle`) instead of id (`ancestorId`)

== The following is the original

The Confluence Publisher allows documentation written in AsciiDoc and versioned directly with the documented code base
to be published to a Confluence space.

It converts the resulting AsciiDoc HTML output to XHTML compatible with
Confluence, manages included resources as Confluence attachments and ensures that only content modified since the last
publication is again re-published.


== Documentation

The documentation of the current release version is published to https://confluence-publisher.atlassian.net/[].

== Contributing

Please see the link:CONTRIBUTING.md[contribution guide] for instructions on how to build the Confluence Publisher locally and what to check before sending a pull request.

== Acknowledgments

https://www.jetbrains.com/?from=confluence-publisher[JetBrains] kindly supports the core developers with free open-source licenses for their products.
