= Confluence Publisher

origin: https://github.com/confluence-publisher/confluence-publisher

== Difference from the original

* This publisher publishes each file on `asciidocRootFolder` with ignoring directory structure by using `directoryStructureStrategy=TITLE_BASE`.
** You MUST write `:parent_title: Title of parent page` on asciidoc file subject to publish when using this strategy.
* You can set specify parent page by title (`ancestorTitle`) instead of id (`ancestorId`)

== The following is the original

The Confluence Publisher allows documentation written in AsciiDoc and versioned directly with the documented code base
to be published to a Confluence space.

It converts the resulting AsciiDoc HTML output to XHTML compatible with
Confluence, manages included resources as Confluence attachments and ensures that only content modified since the last
publication is again re-published.


== Documentation

The documentation of the current release version is published to https://confluence-publisher.atlassian.net/[].

== Contributing

Please see the link:CONTRIBUTING.md[contribution guide] for instructions on how to build the Confluence Publisher locally and what to check before sending a pull request.

== Acknowledgments

https://www.jetbrains.com/?from=confluence-publisher[JetBrains] kindly supports the core developers with free open-source licenses for their products.
